### ISSUE TITLE
Namespace error?

### ISSUE THREAD

**Issue by jward7** [reinteractive/reinteractive-style#3]
I installed this gem as per the recipe on my Ubuntu machine. I run the rubymine IDE. I get the following namespace errors:

![image](https://user-images.githubusercontent.com/6366656/31128035-4820b0fe-a89c-11e7-9a83-f94849276d9e.png)

Does the gem install correctly for others?

**Comment by gizotti** [comment]
@danieldraper looks like some cops namespaces changed on `rubocop 0.50`. 

We'll probably have to check versions to ensure `0.50` and `< 0.50` versions work.

**Comment by gizotti** [comment]
@jward7 a PR has been submitted for to fix this error. Will ping you when the gem can be updated.

**Comment by jward7** [comment]
@gizotti @danieldraper 
I did:
bundle update reinteractive-style
bundle update rubocop
bundle install

I get much fewer errors. However these errors remain:

					Error: The `Lint/InvalidCharacterLiteral` cop has been removed since it was never being actually triggered.
					(obsolete configuration found in /home/justin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reinteractive-style-0.2.2/default.yml, please update it)
					obsolete parameter EnforcedStyle (for Style/Encoding) found in /home/justin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reinteractive-style-0.2.2/default.yml
					Style/Encoding no longer supports styles. The "never" behavior is always assumed.
					obsolete parameter SupportedStyles (for Style/Encoding) found in /home/justin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reinteractive-style-0.2.2/default.yml
					Style/Encoding no longer supports styles. The "never" behavior is always assumed.

**Comment by gizotti** [comment]
@jward7 do you have `rubocop` in your `Gemfile` or is `reinteractive-style` handling the dependency?

**Comment by jward7** [comment]
'reinteractive-style' handling the dependency.
